<?php
/**
 * Incremental language overrides/extensions.
 * Keeps core lang.php minimally touched and allows safe, gradual i18n rollout.
 */

$lang_overrides = [
    'cs' => [
        'lang_en' => 'Angličtina',
        'procurement' => 'Nákupy',
        'role_admin' => 'Admin',
        'role_manager' => 'Manažer',
        'role_engineer' => 'Technik',
        'role_employee' => 'Zaměstnanec',
        'language_switch' => 'Přepnout jazyk',

        'client_section_title' => 'Klientská sekce',
        'client_default_name' => 'Klient',
        'client_hero_title' => 'Stav opravy a cena na jednom místě.',
        'client_hero_subtitle' => 'Tohle je oddělená klientská sekce pro AppleFix. Přihlašuješ se přes číslo zakázky a PIN kód z protokolu, takže admin login zůstává čistě pro servis.',
        'client_order_label' => 'Zakázka',
        'client_label_device' => 'Zařízení',
        'client_label_last_change' => 'Poslední změna',
        'client_label_problem_desc' => 'Popis závady',
        'client_label_serial_number' => 'Sériové číslo / IMEI',
        'client_label_serial_number_2' => 'Druhé číslo / IMEI 2',
        'client_label_received' => 'Přijato',
        'client_media_title' => 'Fotky od technika',
        'client_media_desc' => 'Přehled stavu zařízení a průběhu opravy.',
        'client_media_alt' => 'Fotka zakázky',
        'client_media_caption_default' => 'Fotka technika',
        'client_media_empty' => 'Zatím tu nejsou žádné fotografie k této zakázce.',
        'client_notice_ready' => 'Zařízení je připravené k vyzvednutí nebo už bylo vydáno.',
        'client_notice_waiting_parts' => 'Oprava čeká na díly.',
        'client_notice_in_progress' => 'Technik na zakázce pracuje.',
        'client_no_active_order' => 'Pro tento účet zatím nemáme žádnou aktivní zakázku.',
        'client_my_orders' => 'Moje zakázky',
        'client_repairs_overview' => 'Přehled oprav',
        'client_no_orders' => 'Zatím žádné zakázky.',
        'client_device_fallback' => 'Zařízení',
        'client_amount_final' => 'Konečná cena opravy',
        'client_amount_estimated' => 'Orientační cena opravy',
        'client_amount_generic' => 'Cena',
        'client_status_new' => 'Přijato',
        'client_status_pending_approval' => 'Čeká na schválení',
        'client_status_in_progress' => 'V procesu',
        'client_status_waiting_parts' => 'Čeká na díly',
        'client_status_completed' => 'Připraveno k vyzvednutí',
        'client_status_collected' => 'Vydáno',
        'client_status_cancelled' => 'Zrušeno',

        'login_fill_user_pass' => 'Vyplň uživatele a heslo.',
        'login_invalid_credentials' => 'Neplatný uživatel nebo heslo.',
        'login_headline' => '...servis<br>se vším všudy.',
        'login_point_staff_client' => 'Jeden login portal pro zaměstnance i klienty',
        'login_point_dashboard' => 'Správný dashboard podle přihlášené role',
        'login_point_scope' => 'Klient vidí jen svou opravu a stav zakázky',
        'login_panel_secure_access' => 'Secure Access',
        'login_username_placeholder' => 'E-mail, telefon, číslo zakázky nebo uživatelské jméno',
        'login_password_placeholder' => 'Heslo nebo PIN',
        'login_shared_form_note' => 'Klient se přihlásí telefonem, e-mailem nebo číslem zakázky + PINem.',
        'login_footer_note' => '',

        'print_reception_terms' => 'Zakázka je přijata k opravě. Diagnostika může být zpoplatněna. Záruka na práci je 6 měsíců. Skladování nad 30 dní je zpoplatněno.',
        'status_page_label' => 'Stav',

        'check' => 'Zkontrolovat',
        'checking' => 'Kontroluji...',
        'yes' => 'Ano',
        'no' => 'Ne',
        'imei_check_title' => 'Kontrola IMEI',
        'police_db' => 'Policejní databáze',
        'imei_input_placeholder' => 'Zadejte IMEI (14 nebo 15 číslic)',
        'imei_help_text' => 'CRM kontroluje policejní databázi přímo v aplikaci. iFreeiCloud dostává plné 15místné IMEI, pokud zadáte jen 14 číslic, kontrolní číslice se dopočítá automaticky.',
        'buyout_sheet_purchase_agreement' => 'Výkupní list / Kupní smlouva',
        'pawn_form' => 'Zástavní formulář',
        'ifreeicloud_not_configured' => 'iFreeiCloud není nakonfigurovaný.',
        'ifreeicloud_issue' => 'iFreeiCloud nahlásil chybu nebo požadavek odmítl.',
        'ifreeicloud_success' => 'Kontrola iFreeiCloud byla úspěšně dokončena.',
        'ifreeicloud_inconclusive' => 'Výsledek iFreeiCloud není jednoznačný.',
        'imei_min_digits_warning' => 'Zadejte prosím alespoň 14 číslic IMEI.',
        'imei_check_failed_try_again' => 'Kontrola IMEI se nezdařila. Zkuste to prosím za chvíli znovu.',
        'imei_check_could_not_complete' => 'Kontrolu se nepodařilo dokončit.',
        'imei_result_unknown' => 'Výsledek se nepodařilo jednoznačně určit.',
        'imei_result_found' => 'Toto zařízení je vedené jako odcizené v policejní databázi.',
        'imei_result_not_found' => 'Toto zařízení nebylo nalezeno v policejní databázi.',

        'upload_no_files' => 'Nebyly nahrány žádné soubory.',
        'upload_dir_not_writable' => 'Složka pro nahrávání není zapisovatelná.',
        'upload_no_valid_file' => 'Nepodařilo se nahrát žádný platný soubor.',
        'in_progress_requires_technician' => 'Pro stav „Provádí se“ musí být zakázka přiřazená technikovi.',
        'technician_in_progress_limit_reached' => 'Technik může mít současně maximálně 2 aktivní zakázky ve stavu „Provádí se“.',
        'status_locked_after_collected' => 'Po stavu „Vydáno“ už nelze stav měnit.',
        'status_updated' => 'Stav byl aktualizován.',
        'engineer_rate_label' => 'Hodinová mzda technika',
        'rate_hint' => 'Částka vyplácená technikovi za 1 hodinu práce.',
    ],
    'ru' => [
        'lang_en' => 'Английский',
        'procurement' => 'Закупки',
        'role_admin' => 'Админ',
        'role_manager' => 'Менеджер',
        'role_engineer' => 'Техник',
        'role_employee' => 'Сотрудник',
        'language_switch' => 'Сменить язык',

        'check' => 'Проверить',
        'checking' => 'Проверка...',
        'yes' => 'Да',
        'no' => 'Нет',
        'imei_check_title' => 'Проверка IMEI',
        'police_db' => 'Полицейская база',
        'imei_input_placeholder' => 'Введите IMEI (14 или 15 цифр)',
        'imei_help_text' => 'CRM проверяет полицейскую базу прямо в приложении. iFreeiCloud получает полный 15-значный IMEI, если введёте только 14 цифр, контрольная цифра будет рассчитана автоматически.',
        'buyout_sheet_purchase_agreement' => 'Акт выкупа / Договор купли-продажи',
        'pawn_form' => 'Залоговый бланк',
        'ifreeicloud_not_configured' => 'iFreeiCloud не настроен.',
        'ifreeicloud_issue' => 'iFreeiCloud сообщил об ошибке или отклонил запрос.',
        'ifreeicloud_success' => 'Проверка iFreeiCloud успешно завершена.',
        'ifreeicloud_inconclusive' => 'Результат iFreeiCloud неоднозначный.',
        'imei_min_digits_warning' => 'Введите не менее 14 цифр IMEI.',
        'imei_check_failed_try_again' => 'Проверка IMEI не удалась. Повторите попытку чуть позже.',
        'imei_check_could_not_complete' => 'Не удалось завершить проверку.',
        'imei_result_unknown' => 'Результат не удалось определить однозначно.',
        'imei_result_found' => 'Устройство числится как украденное в полицейской базе.',
        'imei_result_not_found' => 'Устройство не найдено в полицейской базе.',

        'upload_no_files' => 'Файлы не были загружены.',
        'upload_dir_not_writable' => 'Папка для загрузки недоступна для записи.',
        'upload_no_valid_file' => 'Не удалось загрузить ни одного корректного файла.',
        'in_progress_requires_technician' => 'Для статуса «В работе» заказ должен быть назначен технику.',
        'technician_in_progress_limit_reached' => 'У техника может быть одновременно не более 2 активных заказов в статусе «В работе».',
        'status_locked_after_collected' => 'После статуса «Выдан» изменить статус нельзя.',
        'status_updated' => 'Статус обновлен.',
        'engineer_rate_label' => 'Почасовая ставка техника',
        'rate_hint' => 'Сумма, выплачиваемая технику за 1 час работы.',
    ],
    'en' => [
        // Common / navigation
        'dashboard' => 'Dashboard',
        'orders' => 'Orders',
        'customers' => 'Customers',
        'inventory' => 'Inventory',
        'reports' => 'Reports',
        'settings' => 'Settings',
        'accounting' => 'Accounting',
        'procurement' => 'Procurement',
        'logout' => 'Logout',
        'search_placeholder' => 'Search...',
        'client' => 'Client',
        'device_model' => 'Device model',
        'phone' => 'Phone',
        'ico' => 'Company ID',
        'part_name' => 'Part name',
        'sku' => 'SKU',
        'technicians' => 'Technicians',
        'technician' => 'Technician',
        'status' => 'Status',
        'action' => 'Action',
        'actions' => 'Actions',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'close' => 'Close',
        'print' => 'Print',
        'new' => 'New',
        'pending_approval' => 'Pending approval',
        'in_progress' => 'In progress',
        'waiting_parts' => 'Waiting for parts',
        'status_completed' => 'Completed',
        'status_collected' => 'Collected',
        'status_cancelled' => 'Cancelled',
        'new_order' => 'New order',
        'add_customer' => 'Add customer',
        'check_stock' => 'Check stock',
        'recent_orders' => 'Recent orders',
        'all_orders' => 'All orders',
        'date' => 'Date',
        'created' => 'Created',
        'order' => 'Order',
        'cost_est' => 'Estimated cost',
        'problem' => 'Issue description',
        'appearance' => 'Appearance / accessories',
        'pin' => 'PIN / password',

        // Language switching
        'language' => 'Language',
        'language_switch' => 'Switch language',
        'lang_ru' => 'Russian',
        'lang_cs' => 'Czech',
        'lang_en' => 'English',

        // Roles
        'role_admin' => 'Admin',
        'role_manager' => 'Manager',
        'role_engineer' => 'Technician',
        'role_employee' => 'Employee',

        // Login
        'login_title' => 'Sign in',
        'login_btn' => 'Sign in',
        'username_label' => 'Username',
        'password' => 'Password',
        'login_fill_user_pass' => 'Please enter username and password.',
        'login_invalid_credentials' => 'Invalid username or password.',
        'login_headline' => '...service<br>done right.',
        'login_point_staff_client' => 'One login portal for staff and clients',
        'login_point_dashboard' => 'The right dashboard based on your role',
        'login_point_scope' => 'Clients only see their own repair and status',
        'login_panel_secure_access' => 'Secure Access',
        'login_username_placeholder' => 'Email, phone, order number, or username',
        'login_password_placeholder' => 'Password or PIN',
        'login_shared_form_note' => 'Clients can sign in using phone, email, or order number + PIN.',
        'login_footer_note' => '',

        // Client portal
        'client_section_title' => 'Client portal',
        'client_default_name' => 'Client',
        'client_hero_title' => 'Repair status and price in one place.',
        'client_hero_subtitle' => 'This is a dedicated client portal for AppleFix. You sign in with order number and PIN from the protocol, while admin login remains strictly for service staff.',
        'client_order_label' => 'Order',
        'client_label_device' => 'Device',
        'client_label_last_change' => 'Last update',
        'client_label_problem_desc' => 'Issue description',
        'client_label_serial_number' => 'Serial number / IMEI',
        'client_label_serial_number_2' => 'Second serial / IMEI 2',
        'client_label_received' => 'Received',
        'client_media_title' => 'Photos from technician',
        'client_media_desc' => 'Overview of the device condition and repair progress.',
        'client_media_alt' => 'Order photo',
        'client_media_caption_default' => 'Technician photo',
        'client_media_empty' => 'No photos available for this order yet.',
        'client_notice_ready' => 'Your device is ready for pickup or has already been collected.',
        'client_notice_waiting_parts' => 'Repair is waiting for parts.',
        'client_notice_in_progress' => 'A technician is currently working on your order.',
        'client_no_active_order' => 'There is no active order for this account yet.',
        'client_my_orders' => 'My orders',
        'client_repairs_overview' => 'Repair overview',
        'client_no_orders' => 'No orders yet.',
        'client_device_fallback' => 'Device',
        'client_amount_final' => 'Final repair price',
        'client_amount_estimated' => 'Estimated repair price',
        'client_amount_generic' => 'Price',
        'client_status_new' => 'Received',
        'client_status_pending_approval' => 'Pending approval',
        'client_status_in_progress' => 'In progress',
        'client_status_waiting_parts' => 'Waiting for parts',
        'client_status_completed' => 'Ready for pickup',
        'client_status_collected' => 'Collected',
        'client_status_cancelled' => 'Cancelled',

        // Print / misc
        'select_print_language' => 'Select print language',
        'reception_act' => 'Reception protocol',
        'reception_act_thermal' => 'Reception protocol (Thermal)',
        'print_reception_terms' => 'The device is accepted for repair. Diagnostics may be charged. Warranty for workmanship is 6 months. Storage over 30 days may be charged.',
        'status_page_label' => 'Status',

        'check' => 'Check',
        'checking' => 'Checking...',
        'yes' => 'Yes',
        'no' => 'No',
        'imei_check_title' => 'IMEI Check',
        'police_db' => 'Police DB',
        'imei_input_placeholder' => 'Enter IMEI (14 or 15 digits)',
        'imei_help_text' => 'CRM checks the Police database directly in app. iFreeiCloud receives full 15-digit IMEI, if you enter only 14 digits the checksum is auto-calculated.',
        'buyout_sheet_purchase_agreement' => 'Buyout sheet / Purchase agreement',
        'pawn_form' => 'Pawn form',
        'ifreeicloud_not_configured' => 'iFreeiCloud is not configured.',
        'ifreeicloud_issue' => 'iFreeiCloud reported an issue or rejected the request.',
        'ifreeicloud_success' => 'iFreeiCloud check completed successfully.',
        'ifreeicloud_inconclusive' => 'iFreeiCloud result is inconclusive.',
        'imei_min_digits_warning' => 'Please enter at least 14 IMEI digits.',
        'imei_check_failed_try_again' => 'IMEI check failed. Please try again shortly.',
        'imei_check_could_not_complete' => 'The check could not be completed.',
        'imei_result_unknown' => 'The result could not be clearly determined.',
        'imei_result_found' => 'This device is reported stolen in the Police database.',
        'imei_result_not_found' => 'This device was not found in the Police database.',

        'upload_no_files' => 'No files were uploaded.',
        'upload_dir_not_writable' => 'Upload directory is not writable.',
        'upload_no_valid_file' => 'No valid file could be uploaded.',
        'in_progress_requires_technician' => 'To set In Progress, the order must be assigned to a technician.',
        'technician_in_progress_limit_reached' => 'A technician can have at most 2 active in-progress orders at the same time.',
        'status_locked_after_collected' => 'Status cannot be changed after Collected.',
        'status_updated' => 'Status was updated.',
        'engineer_rate_label' => 'Technician hourly wage',
        'rate_hint' => 'Amount paid to technician per 1 hour of work.',
    ],
];
